server:
       port: 8888
       contextPath: /shop
               
       error:
             whitelabel:
                        enabled: false

spring:
       profiles:
                active: dev
       devtools:
                livereload:
                           enabled: true
       http:
            encoding:
                     charset: UTF-8
                     enabled: true
                     forced: true
                     forced-request: true
                     forced-response: true
            multipart:
                      enabled: true
                      max-file-size: 50MB
                      max-request-size: 50MB
                      location: file:/shoppingmall-uploads
       aop:
           auto: true
       aop-proxy-target-class: true


       datasource:
                  driver-class-name: org.mariadb.jdbc.Driver
                  url: jdbc:mariadb://192.168.1.190:3307/shop
                  username: shop
                  password: shop
                  
       mvc:
          view:
               prefix: /WEB-INF/views/
               suffix: .jsp
       restTemplate:
                    factory:
                            readTimeout: 5000
                            connectTimeout: 3000
                    httpClient:
                              maxConnTotal: 100
                              maxConnPerRoute: 5
       static:
              resource:
                       location: file:/shoppingmall-uploads
#security:
#         user:
#              name: test
#              password: 5678
#         oauth2:
#                client:
#                       client-id: pjmall
#                       client-secret: 1234
       